//! Every reader and the cleaning passes, against Open3D 0.19 (plan step S2, gate E2).
//!
//! `tests/data/io_expected.json` is generated by
//! `scratchpad/rust/S2/dump_reference.py`, which reads each file with
//! `open3d.io.read_triangle_mesh`, runs `fragment.load_mesh`'s three cleaning passes and then
//! `fragment.largest_component`, and records the counts, the array checksums and a few global
//! statistics at each of the three stages. Nothing in this file is a hand-written expectation.
//!
//! Two rules the E2 note establishes and this test follows:
//!
//! * **raw counts are only comparable for PLY.** Open3D reads OBJ, STL, OFF and GLB through
//!   Assimp, whose vertex-joining pass returns a vertex list that is neither the file's nor one
//!   per face corner (a 60 000-facet STL comes back with 179 990 vertices, not 180 000). After
//!   cleaning every reader agrees with it exactly.
//! * **an ASCII input cannot be bit-exact with Open3D.** Its `fast_atof` is not correctly rounded,
//!   so OBJ and ASCII STL are compared through order-independent statistics with a tolerance,
//!   while the formats Open3D reads exactly are compared by checksum, in file order.

use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

use sherd_core::io;
use sherd_core::mesh::{Mesh, clean, components};

#[derive(Debug, Deserialize)]
struct Expected {
    open3d_version: String,
    fixtures: Vec<Entry>,
    benchmarks: Vec<Entry>,
}

#[derive(Debug, Deserialize)]
struct Entry {
    path: String,
    format: String,
    /// True when Open3D's own parse is exact, so the arrays must match bit for bit and in order.
    exact: bool,
    raw: Stage,
    clean: Stage,
    largest_component: Stage,
}

#[derive(Debug, Deserialize)]
struct Stage {
    vertices: usize,
    faces: usize,
    colors: bool,
    v_sha256: Option<String>,
    f_sha256: Option<String>,
    c_sha256: Option<String>,
    bbox_min: Option<[f64; 3]>,
    bbox_max: Option<[f64; 3]>,
    centroid: Option<[f64; 3]>,
    area: Option<f64>,
    index_sum: Option<i64>,
    c_mean: Option<[f64; 3]>,
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn expectations() -> Expected {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/io_expected.json");
    let text = std::fs::read_to_string(&path).expect("the expectations are committed");
    serde_json::from_str(&text).expect("the expectations parse")
}

fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    Sha256::digest(bytes).iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

fn v_hash(m: &Mesh) -> String {
    let mut bytes = Vec::with_capacity(m.v.len() * 24);
    for p in &m.v {
        for c in p {
            bytes.extend_from_slice(&c.to_le_bytes());
        }
    }
    hex(&bytes)
}

fn f_hash(m: &Mesh) -> String {
    let mut bytes = Vec::with_capacity(m.f.len() * 12);
    for t in &m.f {
        for i in t {
            bytes.extend_from_slice(&i.to_le_bytes());
        }
    }
    hex(&bytes)
}

fn c_hash(m: &Mesh) -> Option<String> {
    let colors = m.colors.as_ref()?;
    let mut bytes = Vec::with_capacity(colors.len() * 3);
    for c in colors {
        bytes.extend_from_slice(c);
    }
    Some(hex(&bytes))
}

fn bbox(m: &Mesh) -> ([f64; 3], [f64; 3]) {
    let mut lo = [f64::INFINITY; 3];
    let mut hi = [f64::NEG_INFINITY; 3];
    for p in &m.v {
        for k in 0..3 {
            lo[k] = lo[k].min(p[k]);
            hi[k] = hi[k].max(p[k]);
        }
    }
    (lo, hi)
}

fn centroid(m: &Mesh) -> [f64; 3] {
    let mut sum = [0.0_f64; 3];
    for p in &m.v {
        for k in 0..3 {
            sum[k] += p[k];
        }
    }
    #[allow(clippy::cast_precision_loss)]
    let n = m.v.len() as f64;
    sum.map(|s| s / n)
}

fn area(mesh: &Mesh) -> f64 {
    let mut total = 0.0;
    for t in &mesh.f {
        let corner = |k: usize| mesh.v[t[k] as usize];
        let (p0, p1, p2) = (corner(0), corner(1), corner(2));
        let e0 = [p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]];
        let e1 = [p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]];
        let cross = [
            e0[1] * e1[2] - e0[2] * e1[1],
            e0[2] * e1[0] - e0[0] * e1[2],
            e0[0] * e1[1] - e0[1] * e1[0],
        ];
        total += 0.5 * cross.iter().map(|c| c * c).sum::<f64>().sqrt();
    }
    total
}

fn index_sum(m: &Mesh) -> i64 {
    m.f.iter().flatten().map(|&i| i64::from(i)).sum()
}

/// Relative agreement, with an absolute floor so that a coordinate at the origin does not need to
/// be bit-exact.
fn close(a: f64, b: f64, rel: f64, scale: f64) -> bool {
    (a - b).abs() <= rel * scale.max(a.abs().max(b.abs()))
}

fn check(mesh: &Mesh, want: &Stage, exact: bool, what: &str) {
    assert_eq!(mesh.n_vertices(), want.vertices, "{what}: vertex count");
    assert_eq!(mesh.n_faces(), want.faces, "{what}: face count");
    assert_eq!(mesh.has_colors(), want.colors, "{what}: colours present");
    if mesh.n_vertices() == 0 {
        return;
    }
    if exact {
        assert_eq!(&v_hash(mesh), want.v_sha256.as_ref().unwrap(), "{what}: vertices, in order");
        if mesh.n_faces() > 0 {
            assert_eq!(&f_hash(mesh), want.f_sha256.as_ref().unwrap(), "{what}: faces, in order");
        }
        assert_eq!(c_hash(mesh).as_ref(), want.c_sha256.as_ref(), "{what}: colours, in order");
        return;
    }
    // Open3D's vertex order for these formats is Assimp's, not the file's, so only quantities
    // that do not depend on the order are compared.
    let (lo, hi) = bbox(mesh);
    let scale = (0..3).fold(0.0_f64, |s, k| s.max(hi[k] - lo[k]));
    let want_lo = want.bbox_min.expect("a non-empty stage has a bounding box");
    let want_hi = want.bbox_max.expect("a non-empty stage has a bounding box");
    for k in 0..3 {
        assert!(close(lo[k], want_lo[k], 1e-6, scale), "{what}: bbox min[{k}] {lo:?} {want_lo:?}");
        assert!(close(hi[k], want_hi[k], 1e-6, scale), "{what}: bbox max[{k}] {hi:?} {want_hi:?}");
    }
    let c = centroid(mesh);
    let want_c = want.centroid.expect("a non-empty stage has a centroid");
    for k in 0..3 {
        assert!(close(c[k], want_c[k], 1e-6, scale), "{what}: centroid[{k}] {c:?} {want_c:?}");
    }
    if mesh.n_faces() > 0 {
        let a = area(mesh);
        let want_a = want.area.expect("a stage with faces has an area");
        assert!(close(a, want_a, 1e-6, want_a), "{what}: area {a} vs {want_a}");
        assert_eq!(index_sum(mesh), want.index_sum.expect("an index sum"), "{what}: index sum");
    }
    if let Some(colors) = &mesh.colors {
        let want_mean = want.c_mean.expect("a coloured stage has a colour mean");
        #[allow(clippy::cast_precision_loss)]
        let n = colors.len() as f64;
        for k in 0..3 {
            let mean = colors.iter().map(|c| f64::from(c[k])).sum::<f64>() / n;
            assert!(
                (mean - want_mean[k]).abs() < 1e-6,
                "{what}: mean colour[{k}] {mean} vs {}",
                want_mean[k]
            );
        }
    }
}

/// Reads `entry`, checks it at all three stages, and returns false when the file is not in this
/// checkout (the benchmark data is never committed).
///
/// `cross_check_load` re-reads the file through [`io::load_mesh`] and demands the same mesh. It is
/// on for the committed fixtures and off for the benchmark scans, where it would double a run that
/// is already the slowest test in the crate.
fn run(entry: &Entry, cross_check_load: bool) -> bool {
    let path = repo_root().join(&entry.path);
    if !path.exists() {
        eprintln!("skipping {} (not in this checkout)", entry.path);
        return false;
    }
    let mut mesh = io::read_mesh(&path).expect("the file reads");
    if entry.format == "ply" {
        // Only PLY has a raw vertex list Open3D reproduces; see the module comment.
        check(&mesh, &entry.raw, entry.exact, &format!("{} raw", entry.path));
    }
    clean::clean(&mut mesh);
    check(&mesh, &entry.clean, entry.exact, &format!("{} cleaned", entry.path));

    if cross_check_load {
        let loaded = io::load_mesh(&path).expect("the file loads");
        assert_eq!(loaded, mesh, "{}: load_mesh is read_mesh + clean", entry.path);
    }

    components::largest_component(&mut mesh);
    check(&mesh, &entry.largest_component, entry.exact, &format!("{} largest", entry.path));
    true
}

#[test]
fn the_expectations_come_from_the_reference_open3d() {
    assert_eq!(expectations().open3d_version, "0.19.0");
}

#[test]
fn every_format_matches_open3d_on_the_committed_fixtures() {
    let expected = expectations();
    assert!(expected.fixtures.len() >= 12, "the fixture set covers every format");
    let mut seen = std::collections::BTreeSet::new();
    for entry in &expected.fixtures {
        assert!(run(entry, true), "{} is committed and must be there", entry.path);
        seen.insert(entry.format.clone());
    }
    assert_eq!(
        seen,
        ["glb", "obj", "off", "ply", "stl"].iter().map(|s| (*s).to_string()).collect()
    );
}

#[test]
fn every_benchmark_file_matches_open3d() {
    let expected = expectations();
    let mut ran = 0;
    for entry in &expected.benchmarks {
        if run(entry, false) {
            ran += 1;
        }
    }
    eprintln!("{ran} of {} benchmark files were present", expected.benchmarks.len());
}
