// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupDto } from "./GroupDto";
import type { JoinDto } from "./JoinDto";
import type { UnplacedDto } from "./UnplacedDto";

/**
 * What was assembled, by name: the window has the meshes already and needs only the poses.
 */
export type AssemblyDto = { 
/**
 * The groups, largest first, as the engine laid them out.
 */
groups: Array<GroupDto>, 
/**
 * Every placed fragment's pose, row-major, in its group's frame.
 */
poses: { [key in string]: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]] }, 
/**
 * The joins that hold the groups together.
 */
joins: Array<JoinDto>, 
/**
 * Pairs that were candidates and did not make it, with the reason to show.
 */
unplaced: Array<UnplacedDto>, };
