// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The launch sheet's executor (A §7.4), which is `sherd_core::Backend` with serde on it — the
 * engine's own enum has none, deliberately, because it is not part of any file it writes.
 */
export type BackendChoice = "auto" | "cpu" | "gpu";
