// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the last runs on this machine measured — enough to say how long the next one will take.
 *
 * Derived data, cheap to relearn: nothing here is the user's, and A §6 lets a damaged or missing
 * file start again from `karas`'s published ratios rather than fail anything.
 */
export type Calibration = { 
/**
 * [`CALIBRATION_VERSION`].
 */
version: number, 
/**
 * Finished runs that taught it something. Zero means nothing is measured yet.
 */
runs: number, 
/**
 * Seconds one pair costs in matching on this machine.
 */
pair_seconds: number, 
/**
 * Every stage after matching, as a fraction of matching's seconds; keyed by R §11.2's stage
 * name. A §6's `karas` figures until a run of this machine's own replaces them.
 */
ratios: { [key in string]: number }, };
