// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of `candidates.json` (A §4), the index the review screen works from: a row carries
 * everything A §8.3 puts on the screen for one candidate, so that opening a join reads a few
 * hundred kilobytes and never the 54 000 rows of `report.json`.
 *
 * By name and not by [`sherd_core::FragId`]: the index outlives the collection's numbering, and
 * A §8.1's decisions are about names too.
 */
export type CandidateRow = { 
/**
 * The fragment the pose maps *into* (R §4.1's first name).
 */
a: string, 
/**
 * The fragment the pose moves.
 */
b: string, 
/**
 * `T`: `p_a = T · p_b`, row-major — the matrix the viewer puts on **b**.
 */
pose: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]], 
/**
 * R §5.7's ranking key, `seam · tight`: what the queue sorts on.
 */
score: number, 
/**
 * Every number R §6 produced, for the scores panel against its thresholds.
 */
scores: Record<string, number | boolean | null>, 
/**
 * The band it ended in — after the constraints and the object round, which is the band the
 * run acted on.
 */
tier: "confirmed" | "probable" | "rejected", 
/**
 * Whether R §8 built with this pair. Several candidates of a pair routinely converge on one
 * placement, so the flag is the pair's and not one pose's.
 */
used: boolean, 
/**
 * The tier pass's evidence, which is what A §8.3 says «почему не подтверждено» from; `None`
 * where the pass did not run or never probed this candidate.
 */
evidence: Record<string, unknown> | null, };
