// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`sherd_core::tiers::ColourAgreement`] for the bindings, as [`EvidenceTs`] carries it.
 */
export type ColourAgreement = { 
/**
 * CIE76 between the two fragments' fracture-face mean Lab.
 */
frac_delta_e?: number, 
/**
 * Total variation between the two fragments' shell-face Lab histograms, `0`…`1`.
 */
shell_hist?: number, };
