// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

/**
 * `decisions.json`: the decisions as they stand. Undo and redo are the window's.
 */
export type DecisionsFile = { 
/**
 * [`DECISIONS_VERSION`].
 */
version: number, 
/**
 * One per pair.
 */
decisions: Array<Decision>, };
