// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict";

/**
 * One decision.
 */
export type Decision = { 
/**
 * One fragment, by name.
 */
a: string, 
/**
 * The other.
 */
b: string, 
/**
 * What was decided.
 */
verdict: Verdict, 
/**
 * The accepted candidate's pose, four rows of four, `b` into `a`'s frame **as the candidate
 * names them**. Carried here so that a decision outlives the `match.state` it was made on.
 */
pose: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]] | null, 
/**
 * The band the candidate was in when it was decided on.
 */
source: string | null, 
/**
 * Made by «Принять все оставшиеся вероятные» (A §8.4), and undone with it.
 */
bulk: boolean, 
/**
 * RFC 3339.
 */
at: string, 
/**
 * The run it was carried over from (A §8.5).
 */
carried_from: string | null, };
