// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What matched: D §4.3's engine block.
 */
export type EngineInfo = { 
/**
 * `sherd-core`'s version.
 */
core_version: string, 
/**
 * The algorithm reference it implements.
 */
algo_ref: string, 
/**
 * The commit it was built from.
 */
commit: string, 
/**
 * `cpu`, or `gpu:<adapter>`.
 */
backend: string, };
