// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssemblyDto } from "./AssemblyDto";
import type { Decision } from "./Decision";
import type { EngineInfo } from "./EngineInfo";
import type { FailKind } from "./FailKind";
import type { FragmentInfo } from "./FragmentInfo";
import type { PairDetailDto } from "./PairDetailDto";
import type { RunCounts } from "./RunCounts";

/**
 * What a worker says. One line each, in the order they happened.
 */
export type Event = { "event": "hello", 
/**
 * [`PROTOCOL`].
 */
protocol: number, 
/**
 * `sherd-core`'s version.
 */
core_version: string, 
/**
 * The algorithm reference it implements.
 */
algo_ref: string, 
/**
 * The commit it was built from.
 */
commit: string, } | { "event": "info", 
/**
 * What `sherd-refit-rs info` prints about this build's executors.
 */
backends: Array<string>, 
/**
 * The self-test's lines, empty when it was not asked for.
 */
selftest: Array<string>, } | { "event": "stage", 
/**
 * R §11.2's stage name.
 */
name: string, } | { "event": "progress", 
/**
 * Which stage.
 */
stage: string, 
/**
 * Units finished.
 */
done: number, 
/**
 * Units in the stage.
 */
total: number, } | { "event": "fragment_ready" } & FragmentInfo | { "event": "ready", 
/**
 * Fragments loaded.
 */
fragments: number, 
/**
 * Candidates the saved match holds.
 */
candidates: number, } | { "event": "assembly" } & AssemblyDto | { "event": "pair_detail" } & PairDetailDto | { "event": "dropped", 
/**
 * The decisions that were not applied, as they stand in the file.
 */
decisions: Array<Decision>, } | { "event": "request_failed", 
/**
 * Why, in the engine's words.
 */
message: string, } | { "event": "exported", 
/**
 * The folder it was written into, as the window shows it and reveals it.
 */
dest: string, 
/**
 * Every file written, relative to `dest` and with `/` between the parts whatever the
 * platform — a list the window counts and prints, not a path it opens.
 */
files: Array<string>, 
/**
 * What they came to on disk, in bytes.
 */
bytes: number, } | { "event": "done", 
/**
 * What the run found.
 */
counts: RunCounts | null, 
/**
 * What ran it.
 */
engine: EngineInfo | null, 
/**
 * Every threshold it resolved to.
 */
params: Record<string, unknown> | null, } | { "event": "failed", 
/**
 * Why, by class.
 */
kind: FailKind, 
/**
 * Why, in the engine's words.
 */
message: string, };
