// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColourAgreement } from "./ColourAgreement";

/**
 * [`sherd_core::tiers::Evidence`], field for field, for the TypeScript bindings only.
 *
 * This is what A §8.3's «Почему не подтверждён сам» is written from — `failed` above all, which
 * the window turns into sentences — and what says why a confirmed join is confirmed (`arm`). As
 * [`ScoresTs`], with a test against the engine's own keys.
 *
 * Every field the engine leaves out of the JSON when it has nothing to say is optional here, and
 * for the same reason: a run that probed no rival writes no `margin`, and a window that read
 * `0` there would show a number the engine never measured.
 */
export type Evidence = { 
/**
 * `score / rival_score` over a second placement that scores.
 */
margin?: number, 
/**
 * How far that second placement puts the sherd, in `t`.
 */
rival_moved_t?: number, 
/**
 * The same ratio over the wide second placement (R §5.6's full list, then stage 1).
 */
wide_margin?: number, 
/**
 * How far the wide second placement puts the sherd from **this** candidate, in `t`.
 */
wide_rival_moved_t?: number, 
/**
 * The same distance from the pair's best candidate, in `t`.
 */
wide_rival_pair_t?: number, 
/**
 * Where the wide second placement was found.
 */
wide_rival_source?: "stage2" | "stage1", 
/**
 * Whether R §6.5 would accept that second placement itself.
 */
wide_rival_accepted?: boolean, 
/**
 * Distinct placements the pair's kept list makes.
 */
placements: number, 
/**
 * Worst rotation over the twelve one-ULP neighbours, in degrees.
 */
determined_deg?: number, 
/**
 * The same in translation, in `t`.
 */
determined_t?: number, 
/**
 * How far the pose stays away after a ±0.5 t push along the seam, in `t`.
 */
slide_t?: number, 
/**
 * Smallest `tight` over the three draws.
 */
resample_tight_min: number, 
/**
 * Largest `gap` over the three draws, in `t`.
 */
resample_gap_max: number, 
/**
 * How many of the three draws R §6.5 accepts.
 */
resample_accept: number, 
/**
 * Independent accepted joins that agree with this placement.
 */
support: number, 
/**
 * The tier's tests this candidate failed; left out on a confirmed join. A §8.3 turns each of
 * these into a sentence (`state/reasons.ts`).
 */
failed?: Array<string>, 
/**
 * Which distinguishing arm confirmed this candidate — `support`, `margin` or `research`.
 */
arm?: string, 
/**
 * How many of this candidate's re-searches landed on its placement, and how many were run.
 */
research?: [number, number], 
/**
 * Task S2's colour agreement across the seam — reported, never gated.
 */
colour?: ColourAgreement, };
