// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A §9.1's two kinds of export, which are the two shapes of `RunOptions` the engine's writers
 * take: everything a `sherd-refit-rs run` writes, or the same without a single mesh.
 *
 * The engine's switches do not separate `scene.glb` from `placed/`, which is why this is two
 * kinds with three opt-ins and not five checkboxes: `write_meshes` turns the lot on, and the
 * three that are left are the ones a run's own flags have (`--placed-all`, `--merged-meshes`,
 * and R §11.5's previews).
 */
export type ExportWhat = { "kind": "folder", 
/**
 * `--placed-all`: a `placed/<name>.ply` for every fragment, not only the assembled ones.
 */
placed_all: boolean, 
/**
 * `--merged-meshes`: R §11.4's `assembly_<k>.ply`, one per group of two or more.
 */
merged_meshes: boolean, 
/**
 * R §11.5's group previews.
 */
previews: boolean, } | { "kind": "tables" };
