// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One scan as the snapshot saw it.
 */
export type FileStamp = { 
/**
 * The fragment's name (R §2) — what every decision, cache and display mesh is keyed by.
 */
name: string, 
/**
 * The file's name in the input folder.
 */
file: string, 
/**
 * Bytes.
 */
size: number, 
/**
 * Modification time, milliseconds since the epoch; 0 where the file system has none.
 */
mtime_ms: number, };
