// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`sherd_core::report::FragmentStats`], field for field, for the TypeScript bindings only: the
 * engine's type cannot derive `TS` from here, and A §2.2's wire contract must still have one
 * source. [`crate::view`]'s tests compare the two field by field, so a field added to the
 * engine's row and forgotten here fails the app's own test suite rather than the window.
 */
export type FragmentStats = { 
/**
 * The fragment's name in the collection.
 */
name: string, 
/**
 * Faces of the working mesh.
 */
faces: number, 
/**
 * Faces of the file, after R §3.1's cleaning and before the largest-component pass.
 */
orig_faces: number, 
/**
 * Vertices of the same.
 */
orig_vertices: number, 
/**
 * R §3.2's wall thickness.
 */
thickness: number, 
/**
 * R §3.2's unfiltered ray mode.
 */
thickness_mode: number, 
/**
 * R §3.3's `res`.
 */
resolution: number, 
/**
 * R §3.3.2's verdict.
 */
watertight: boolean, 
/**
 * The working mesh's bounding-box side lengths.
 */
extent: [number, number, number], 
/**
 * Total area of the working mesh.
 */
area: number, 
/**
 * Fracture area over total area (R §3.4).
 */
fracture_area_fraction: number, };
