// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FragmentStats } from "./FragmentStats";
import type { Warning } from "./Warning";

/**
 * One preprocessed fragment, as the window's collection table shows it (A §5).
 */
export type FragmentInfo = { 
/**
 * The fragment's name (R §2).
 */
name: string, 
/**
 * Its file's name in the input folder.
 */
file: string, 
/**
 * Bytes, for the input snapshot the host keeps (A §4).
 */
size: number, 
/**
 * Modification time, milliseconds since the epoch.
 */
mtime_ms: number, 
/**
 * R §11.3's fragment row.
 */
stats: FragmentStats, 
/**
 * What the window should say about it in red.
 */
warnings: Array<Warning>, 
/**
 * Whether the scan carries per-vertex colour, which decides how its mesh is drawn.
 */
coloured: boolean, 
/**
 * Faces of the display mesh that was written for it.
 */
display_faces: number, };
