// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One assembled group.
 */
export type GroupDto = { 
/**
 * Its fragments, by name.
 */
members: Array<string>, 
/**
 * Whether R §8.2's refinement has run on it.
 */
refined: boolean, };
