// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the scans are (A §5). Three states, not an `Option`: «no folder linked» and «the linked
 * folder is gone» are different rows of A §5's table — the first asks for a folder, the second
 * keeps the results open and turns runs off — so the window must be able to tell them apart.
 */
export type InputView = { 
/**
 * Whether the workspace names an input folder at all.
 */
linked: boolean, 
/**
 * The folder as it resolves now, for the window to show; `None` when it does not resolve.
 */
path: string | null, 
/**
 * Whether the folder can be reached now (A §5, «вход недоступен»).
 */
available: boolean, };
