// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";

/**
 * The input as it stood.
 */
export type InputSnapshot = { 
/**
 * Every scan of the folder, the excluded ones included, in R §2's order.
 */
files: Array<FileStamp>, 
/**
 * The workspace's exclusions at the time.
 */
excluded: Array<string>, };
