// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of job a worker is on (A §5). The window shows a different progress strip for each.
 */
export type JobKind = "prepare" | "run" | "review";
