// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";

/**
 * The job that is running, if one is (A §5's «preparing» and «running» rows). The host owns this
 * — the view is built with it rather than reading it off the disk, because a running job is a
 * fact about this process and not about the workspace folder.
 */
export type JobView = { 
/**
 * What it is doing.
 */
kind: JobKind, 
/**
 * The run it is writing, for a [`JobKind::Run`]; `None` for a `Prepare`.
 */
run_id: string | null, };
