// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One join of a group.
 */
export type JoinDto = { 
/**
 * One fragment.
 */
a: string, 
/**
 * The other.
 */
b: string, };
