// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineInfo } from "./EngineInfo";
import type { FailKind } from "./FailKind";
import type { RunCounts } from "./RunCounts";

/**
 * How a job ended, as the host files it (A §10).
 */
export type Outcome = { "Done": { 
/**
 * What the run found.
 */
counts: RunCounts | null, 
/**
 * What ran it.
 */
engine: EngineInfo | null, 
/**
 * Every threshold it resolved to.
 */
params: Record<string, unknown> | null, } } | { "Failed": { 
/**
 * Why, by class.
 */
kind: FailKind, 
/**
 * Why, in the engine's words.
 */
message: string, } };
