// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The seam of one placement, as the «Ревью» screen draws it (A §2.2's `PairDetail`, A §8.3):
 * [`sherd_core::review::SeamView`] on the wire.
 *
 * `f32` triples and not `f64`: every number here goes straight into a `THREE.BufferAttribute`,
 * which is `Float32Array`, and B's fracture samples are five thousand points — half the JSON for
 * the same picture. The two limits stay `f64` because they are printed, not drawn.
 */
export type PairDetailDto = { 
/**
 * The fragment the pose maps into, drawn at the identity.
 */
a: string, 
/**
 * The fragment the pose moves.
 */
b: string, 
/**
 * B's fracture samples at the pose, in A's frame (R §3.5.2).
 */
contact: Array<[number, number, number]>, 
/**
 * One class per contact point: 0 under the tight limit, 1 under the gap limit, 2 beyond
 * (R §6.1, R §6.5) — the green, yellow and red of the engine's own review images.
 */
contact_class: Array<number>, 
/**
 * Centres of R §6.2's seam voxels, in A's frame.
 */
seam: Array<[number, number, number]>, 
/**
 * The pair's tight limit, in the meshes' own length unit (R §1.2).
 */
tight: number, 
/**
 * The pair's gap limit, in the same unit.
 */
gap: number, };
