// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of A §7.4's three buttons the sheet came from. It changes nothing the engine reads — the
 * thresholds below are the whole truth — and is carried so the history can say what was asked.
 */
export type Preset = "standard" | "thorough" | "custom";
