// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`Resolution`] as the window asks for it (A §9.2's two menu items).
 *
 * A mirror and not serde on [`Resolution`] itself, for [`ScopeDto`]'s reason.
 */
export type ResolutionDto = "full" | "display";
