// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageTime } from "./StageTime";

/**
 * What a finished run found — the numbers the history and the mode tabs show.
 */
export type RunCounts = { 
/**
 * Fragments in the run.
 */
fragments: number, 
/**
 * Pairs matched.
 */
pairs: number, 
/**
 * Pairs R §4.1's wall-ratio filter skipped.
 */
skipped_pairs: number, 
/**
 * Candidates scored.
 */
candidates: number, 
/**
 * Confirmed joins (with the tier off: accepted ones).
 */
confirmed: number, 
/**
 * Probable joins.
 */
probable: number, 
/**
 * Groups of two or more.
 */
groups: number, 
/**
 * Fragments in no group.
 */
unassembled: number, 
/**
 * R §11.2's timings, in the order the stages finished.
 */
timings: Array<StageTime>, };
