// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineInfo } from "./EngineInfo";
import type { InputSnapshot } from "./InputSnapshot";
import type { RunCounts } from "./RunCounts";
import type { RunStatus } from "./RunStatus";

/**
 * `run.json`.
 */
export type RunFile = { 
/**
 * [`RUN_VERSION`].
 */
version: number, 
/**
 * The folder's name.
 */
id: string, 
/**
 * RFC 3339, local offset.
 */
created: string, 
/**
 * When it ended, however it ended.
 */
finished: string | null, 
/**
 * Where it is in its life.
 */
status: RunStatus, 
/**
 * The launch sheet, as the window sent it.
 */
spec: Record<string, unknown>, 
/**
 * Every threshold it resolved to; filled when the run ends.
 */
params: Record<string, unknown> | null, 
/**
 * The input it ran on (A §4, «Stale»).
 */
input: InputSnapshot, 
/**
 * What matched.
 */
engine: EngineInfo | null, 
/**
 * What it found.
 */
counts: RunCounts | null, 
/**
 * The run whose decisions it started from (A §8.5).
 */
carried_from: string | null, };
