// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendChoice } from "./BackendChoice";
import type { Preset } from "./Preset";

/**
 * The subset of `RunOptions` the window sets (A §7.4); everything else is `RunOptions::default()`.
 */
export type RunSpec = { 
/**
 * Which button the sheet came from.
 */
preset: Preset, 
/**
 * The executor asked for.
 */
backend: BackendChoice, 
/**
 * The adapter, when the user picked one by name.
 */
adapter: string | null, 
/**
 * The GPU memory budget in gigabytes, or `None` for the backend's own guess.
 */
gpu_memory_gb: number | null, 
/**
 * R §10's seed.
 */
seed: number, 
/**
 * Faces of the working mesh.
 */
target_faces: number, 
/**
 * Whether the confidence tier runs at all (`Params::tiers`).
 */
tiers: boolean, 
/**
 * Independent agreeing paths the tier's support arm wants (`Thresholds::agree_seeds`).
 */
agree_seeds: number, 
/**
 * R §4.1's wall-ratio filter.
 */
thick_ratio: number, 
/**
 * R §6.5's tight-contact fraction.
 */
min_tight: number, 
/**
 * R §6.5's median gap, in `t`.
 */
max_gap: number, 
/**
 * R §6.5's penetration fraction.
 */
max_pen: number, 
/**
 * R §6.5's shortest shared seam, in `t`.
 */
min_seam: number, 
/**
 * Worker threads; 0 is rayon's default.
 */
workers: number, 
/**
 * The memory budget in gigabytes, or `None` for the machine's.
 */
memory_gb: number | null, };
