// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailKind } from "./FailKind";

/**
 * Where a run is in its life.
 */
export type RunStatus = { "state": "running" } | { "state": "done" } | { "state": "cancelled" } | { "state": "failed", 
/**
 * Why, by class.
 */
kind: FailKind, 
/**
 * Why, in the engine's words.
 */
message: string, } | { "state": "interrupted" };
