// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunFile } from "./RunFile";
import type { StaleDiff } from "./StaleDiff";

/**
 * One run of the history, with what has changed under it since (A §5, «stale»). The staleness is
 * computed here and not on the frontend because it is a fact about the disk, and the window is
 * not allowed to walk the input folder itself (A §2.1).
 */
export type RunView = { 
/**
 * The run's own `run.json`.
 */
run: RunFile, 
/**
 * What the input has done since the run was made; empty when nothing has.
 */
stale: StaleDiff, };
