// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`Scope`] as the window asks for it: «вся сборка» from the export menu, or «эта группа» from
 * the group inspector.
 *
 * A mirror rather than serde and `ts-rs` on [`Scope`] itself, because the two are not the same
 * thing: [`Scope`] is an argument of a pure function that knows nothing of any window, and this
 * is a shape on a wire, tagged the way [`crate::protocol::ExportWhat`] is so that the window
 * reads one style of union throughout. Nothing of this ever reaches the engine's process — «в
 * Blender» is the shell's own work (A §9.2) — which is why it lives here and not in
 * [`crate::protocol`].
 */
export type ScopeDto = { "kind": "all" } | { "kind": "group", 
/**
 * Its index in [`AssemblyDto::groups`], as the window prints it.
 */
index: number, };
