// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`sherd_core::matching::verify::Scores`], field for field, for the TypeScript bindings only.
 *
 * The same arrangement and the same reason as [`FragmentStatsTs`], and the same test keeping it
 * honest: A §8.3's scores panel puts each of these numbers against its threshold and colours it,
 * and a `Record<string, number>` is not a contract that can be written against — a renamed key
 * would reach the window as a blank cell instead of a compile error.
 *
 * The two flags carry the engine's own JSON shape: left out unless they are set, and written as
 * `1.0` when they are (`verify::as_one`), which is why they are numbers here and not booleans.
 */
export type Scores = { 
/**
 * Fraction of A's facing fracture samples within the tight limit of B's surface (R §6.1).
 */
tightA: number, 
/**
 * The same for B's samples against A's.
 */
tightB: number, 
/**
 * `min(tightA, tightB)` — the side that fits worse is the fit.
 */
tight: number, 
/**
 * Median distance of A's facing samples to B's fracture surface, in `t`.
 */
gapA: number, 
/**
 * The same for B.
 */
gapB: number, 
/**
 * `max(gapA, gapB)`, in `t`.
 */
gap: number, 
/**
 * Area of A in contact with B, in `t²`.
 */
contactA: number, 
/**
 * The same for B.
 */
contactB: number, 
/**
 * `min(contactA, contactB)`, in `t²`.
 */
contact: number, 
/**
 * Length of the shared seam, in `t` (R §6.2).
 */
seam: number, 
/**
 * The pair's own gap limit, in `t` — what `gap` is shown against.
 */
gap_limit: number, 
/**
 * The distance `tight` counted, in `t`.
 */
tight_delta: number, 
/**
 * Median step height of the outer shell across the seam, in `t` (R §6.3).
 */
cont: number, 
/**
 * Median agreement of the two shells' normals across the seam (R §6.3).
 */
cont_n: number, 
/**
 * Fraction of surface samples of either fragment inside the other (R §6.4).
 */
pen: number, 
/**
 * Deepest excursion of either fragment into the other, in `t` (R §6.4).
 */
pen_depth: number, 
/**
 * `1` when a fragment is not watertight and R §6.4 could not run; absent otherwise.
 */
pen_unavailable?: number, 
/**
 * `1` when only the cheap half of R §6 was computed; absent otherwise.
 */
partial?: number, 
/**
 * R §5.4's re-score of the stage-1 pose this candidate was refined from.
 */
brk: number, 
/**
 * The best stage-1 re-score of the whole pair (R §5.7).
 */
brk_best: number, };
