// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendChoice } from "./BackendChoice";

/**
 * What the app remembers about this computer (A §11).
 */
export type Settings = { 
/**
 * [`SETTINGS_VERSION`].
 */
version: number, 
/**
 * The executor a launch sheet starts on (A §7.4), when the workspace has no sheet of its own
 * to repeat.
 */
backend: BackendChoice, 
/**
 * The memory budget in gigabytes, or `None` for D §5's default — half of what the machine
 * has. A §11's «лимит памяти».
 */
memory_gb: number | null, 
/**
 * Worker threads; `0` is rayon's own default, which is every core.
 */
workers: number, 
/**
 * Where Blender is on this machine (A §9.2), when it is not where
 * [`crate::blender::find_blender`] looks.
 */
blender_path: string | null, };
