// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stage's wall clock.
 */
export type StageTime = { 
/**
 * R §11.2's stage name.
 */
stage: string, 
/**
 * Seconds.
 */
seconds: number, };
