// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How two snapshots differ, by fragment name.
 */
export type StaleDiff = { 
/**
 * Scans that are there now and were not.
 */
added: Array<string>, 
/**
 * Scans that were there and are not.
 */
removed: Array<string>, 
/**
 * Scans whose size or modification time changed.
 */
changed: Array<string>, 
/**
 * Fragments excluded since.
 */
excluded_added: Array<string>, 
/**
 * Fragments taken back in since.
 */
excluded_removed: Array<string>, };
