// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pair the assembly did not use, and why.
 */
export type UnplacedDto = { 
/**
 * One fragment.
 */
a: string, 
/**
 * The other.
 */
b: string, 
/**
 * What to tell the reviewer — the tier's refusal, or the conflict that dropped it.
 */
reason: string, };
