// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something worth telling the reviewer about one fragment (A §5).
 */
export type Warning = { "warning": "thickness_outlier", 
/**
 * This fragment's wall.
 */
thickness: number, 
/**
 * The collection's median.
 */
median: number, } | { "warning": "not_watertight" };
