// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";
import type { FragmentInfo } from "./FragmentInfo";
import type { InputView } from "./InputView";
import type { JobView } from "./JobView";
import type { RunView } from "./RunView";

/**
 * Everything the window knows about the open workspace (A §5).
 *
 * One value, and one command that returns it: every screen of the app derives what it shows from
 * this and from the events of the running job, so there is never a second opinion about the
 * workspace to keep in step with the first.
 */
export type WorkspaceView = { 
/**
 * The workspace folder, as text — the window shows it and never walks it (A §2.1).
 */
root: string, 
/**
 * The folder's own name, which is what the title bar calls the workspace.
 */
name: string, 
/**
 * Where the scans are.
 */
input: InputView, 
/**
 * Fragments left out of every run (A §5.1), by name.
 */
excluded: Array<string>, 
/**
 * Every scan of the input folder as it stands now, the excluded ones included; empty when the
 * input is not available.
 */
files: Array<FileStamp>, 
/**
 * The rows `fragments/index.json` holds — what the last `Prepare` produced.
 */
fragments: Array<FragmentInfo>, 
/**
 * Whether the input needs no `Prepare`; see [`prepared`].
 */
prepared: boolean, 
/**
 * The history, newest first.
 */
runs: Array<RunView>, 
/**
 * `fragments/`, as text: the window asks Tauri's asset protocol for meshes and thumbnails
 * under it, and is given nothing outside the workspace (A §2.1).
 */
fragments_dir: string, 
/**
 * The job a worker is on, if any.
 */
job: JobView | null, };
